name: CI Workflow

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - master
      - release/*
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Гизатуллин Фарид Тахирович"
      GROUP_NUMBER: "M3113"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print developer info
        run: |
          echo "Full Name: $env.FULL_NAME, Group: $env.GROUP_NUMBER, GitHub Username: $github.actor"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests
        run: |
          python -m unittest discover -s test
